spring.application.name=SimpleSpringbootApp
logging.level.org.springframework.boot.autoconfigure.jdbc=debug
spring.datasource.driver-classname=com.mysql.cj.jdbc.Driver

spring.datasource.username=root
spring.datasource.password=Root@123

spring.jpa.hibernate.ddl-auto = update
spring.datasource.url=jdbc:mysql://localhost:3306/meterTable?useSSl = false

